-- Exploratory Data Analysis - SQL

-- 1.What is the total revenue by year?
SELECT SUBSTRING(`order_date`,1,7) AS `month`, SUM(revenue) AS revenue
FROM orders_staging
GROUP BY `month`
ORDER BY 1 ASC;

-- 2.What is the total revenue generated by male vs. female customers?
SELECT cust.gender, SUM(revenue) AS total_revenue, 
AVG(revenue) AS avg_revenue, 
MAX(revenue) AS max_revenue, 
MIN(revenue) AS min_revenue
FROM orders_staging ord 
INNER JOIN customers cust
	ON ord.customer_id = cust.customer_id
GROUP BY gender
ORDER BY gender DESC;

-- 3.What is the revenue contribution of each age group? 
SELECT age_group, SUM(revenue) AS total_revenue
FROM orders_staging ord 
INNER JOIN customers cust
	ON ord.customer_id = cust.customer_id
GROUP BY age_group
ORDER BY total_revenue DESC;

-- 4.Which city generated the most highest revenue?
SELECT ord.customer_id, cust.city, SUM(revenue) as total_revenue
FROM orders_staging ord 
INNER JOIN customers cust
	ON ord.customer_id = cust.customer_id
GROUP BY customer_id, city
ORDER BY total_revenue desc
LIMIT 5;

-- 5.Which are top 5 products with the highest revenue?
SELECT product_name, SUM(revenue) AS total_revenue
FROM orders_staging ord 
INNER JOIN customers cust
	ON ord.customer_id = cust.customer_id
INNER JOIN products pro
	ON ord.product_id = pro.product_id
GROUP BY product_name
ORDER BY total_revenue DESC
limit 5;

-- 6.Do loyalty members spend more? Compare average spend and total revenue between loyalty members and non-loyalty members.
SELECT loyalty_member, 
	   COUNT(ord.customer_id) AS total_customers, 
       ROUND(AVG(revenue),2) AS avg_spend, 
       ROUND(SUM(revenue),2) AS total_revenue
FROM customers cust
	INNER JOIN orders_staging ord
	ON cust.customer_id = ord.customer_id 
INNER JOIN products pro
	ON ord.product_id = pro.product_id
GROUP BY loyalty_member
ORDER BY total_revenue, avg_spend DESC;

-- 7.Has the number of loyalty members increased year by year?
SELECT SUBSTRING(`signup_date`,1,7) AS `month`, COUNT(loyalty_member) AS total_loyalty_member
FROM customers
WHERE loyalty_member = 'Yes'
GROUP BY `month`
ORDER BY `month` ASC;

-- 8. What are the top 3 most purchased products within each category? 
WITH item_counts AS (
    SELECT pro.category, 
           pro.product_name,
           COUNT(ord.customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY pro.category ORDER BY COUNT(ord.customer_id) DESC) AS item_rank
    FROM orders_staging ord
    INNER JOIN products pro
		ON ord.product_id = pro.product_id
    GROUP BY category, quantity, product_name
)
SELECT item_rank, category, product_name, total_orders
FROM item_counts
WHERE item_rank <=3;
